(load-file "~/.emacs.d/local_lisp/global-defs.el")
(load-file "~/.emacs.d/local_lisp/global-state.el")
(load-file "~/.emacs.d/local_lisp/org-ext.el")
(load-file "~/.emacs.d/local_lisp/python-ext.el")
(load-file "~/.emacs.d/local_lisp/mu4e-ext.el")
